adminka/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *

urlpatterns = [
    path('add_product', add_product, name='add_product'),
    path('a_product/<int:id>', admin_product, name='a_product'),
    path('del_product/<int:id>', delete_product, name='del_product'),
    path('a_user', a_user, name='a_user'),
    path('a_orders', a_orders, name='a_orders'),
    path('a_brend', a_brend, name='a_brend'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopDiplom/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('www.urls')),
    path('authreg', include('authreg.urls')),
    path('orders', include('orders.urls')),
    path('adminka', include('adminka.urls')),
path('ratings/', include('star_ratings.urls', namespace='ratings')),
]

www/urls.py
from www.views import *
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', index, name='index'),
    path('shop', shop, name='shop'),  # This path does not require a category_id
    path('stocks', stocks, name='stocks'),
    path('cart', cart, name='cart'),
    path('remove_cart_item/<int:item_id>', remove_cart_item, name='remove_cart_item'),
    path('update_cart_item/<int:item_id>', update_cart_item, name='update_cart_item'),
    path('shop_single/<int:id>', shop_single, name='shop_single'),
    path('acc', acc, name='acc'),
    path('about', about, name='about'),
    path('orders', orders, name='orders'),
    path('products/category/<int:category_id>/', shop, name='products_by_category'),
    path('product/<int:id>/add_comment/', add_comment, name='add_comment'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminka/models.py
from django.db import models

# Create your models here.

www/models.py
from django.contrib.contenttypes.fields import GenericRelation
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from star_ratings.models import Rating

from authreg.models import CustomUser


class Category(models.Model):
    name = models.CharField(null=True, blank=True)

    def __str__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField(max_length=100)
    category = models.ManyToManyField(Category)

    def __str__(self):
        return self.name

class Product(models.Model):
    photo = models.FileField(upload_to='image')
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.IntegerField()
    quantity = models.IntegerField()
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # Сначала сохраняем продукт

        if self.brand and self.category and not self.brand.category.filter(id=self.category.id).exists():
            self.brand.category.add(self.category)

class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    text = models.TextField()
    rating = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        default=5
    )
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.user.username

adminka/forms.py
from django import forms

from www.models import *


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['photo', 'name', 'description', 'price', 'quantity', 'category', 'brand']


class BrandForm(forms.ModelForm):
    class Meta:
        model = Brand
        fields = ['name']

adminka/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404, redirect
from pyexpat.errors import messages

from adminka.forms import ProductForm, BrandForm
from authreg.models import CustomUser
from orders.models import Orders, Status
from www.models import *


def add_product(request):
    categories = Category.objects.all()  # Получаем все категории
    brands = Brand.objects.all()  # Получаем все бренды
    if request.method == 'POST':
        name = request.POST.get('name')
        price = request.POST.get('price')
        description = request.POST.get('description')
        photo = request.FILES.get('photo')
        quantity = request.POST.get('quantity')
        category_id = request.POST.get('category')  # Получаем выбранную категорию
        brand_id = request.POST.get('brand')  # Получаем выбранный бренд

        # Проверка на наличие всех необходимых полей
        if not all([name, price, description, quantity, photo, category_id, brand_id]):
            messages.error(request, 'Пожалуйста, заполните все поля.')
            return render(request, 'adminka/adminka.html', {'categories': categories, 'brands': brands})

        # Создание нового продукта
        product = Product(
            name=name,
            price=price,
            description=description,
            photo=photo,
            quantity=quantity,
            brand_id=brand_id,  # Привязываем выбранный бренд к продукту
            category_id=category_id  # Привязываем выбранную категорию к продукту
        )
        product.save()

        return redirect('index')  # Перенаправление на страницу со списком товаров

    return render(request, 'adminka/adminka.html', {'categories': categories, 'brands': brands})


def admin_product(request, id):
    product = get_object_or_404(Product, id=id)
    categories = Category.objects.all()
    brands = Brand.objects.all()

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = ProductForm(instance=product)

    context = {
        'form': form,
        'product': product,
        'categories': categories,
        'brands': brands
    }

    return render(request, 'adminka/a_product.html', context)


def delete_product(request, id):
    product = get_object_or_404(Product, id=id)
    product.delete()
    return redirect('index')


def a_user(request):
    users = CustomUser.objects.all()
    context = {
        'users': users
    }
    return render(request, 'adminka/a_user.html', context)


def a_brend(request):
    brands = Brand.objects.all()

    if request.method == 'POST':
        if 'add_brand' in request.POST:
            form = BrandForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('a_brend')  # Redirect to the same page after adding
        elif 'delete_brand' in request.POST:
            brand_id = request.POST.get('brand_id')
            brand = get_object_or_404(Brand, id=brand_id)
            brand.delete()
            return redirect('a_brend')  # Redirect to the same page after deletion

    context = {
        'brands': brands,
        'form': BrandForm()  # Pass the form to the template
    }
    return render(request, 'adminka/a_brend.html', context)


def a_orders(request):
    if request.method == 'POST':
        order_id = request.POST.get('order_id')
        status_id = request.POST.get('status_id')

        order = get_object_or_404(Orders, id=order_id)
        status = get_object_or_404(Status, id=status_id)

        order.status = status
        order.save()

        # Отправка письма, если статус "доставлен"
        if status.name.lower() == 'доставлен':
            subject = f'Заказ {order.order_number} доставлен'
            message = f'Ваш заказ №{order.order_number} был успешно доставлен. Назовите номер заказа сотруднику для получения.'
            from_email = 'your-email@example.com'  # Обычно берется из settings.DEFAULT_FROM_EMAIL
            recipient_list = [order.username.email]

            try:
                send_mail(subject, message, from_email, recipient_list, fail_silently=False)
            except Exception as e:
                print(f"Ошибка при отправке почты: {e}")

        return redirect('a_orders')

    order = Orders.objects.all().order_by('-created_at')
    statuses = Status.objects.all()
    context = {
        'order': order,
        'statuses': statuses
    }
    return render(request, 'adminka/a_orders.html', context)

templates/adminka/a_brend.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container mt-5">
        <h2 class="text-white text-center mb-4">Список Брендов</h2>

        <form class="text-white" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label  for="id_name">Добавить новый бренд:</label>
                <input type="text" name="name" class="form-control" id="id_name" required>
            </div>
            <button type="submit" name="add_brand" class="btn btn-border">Добавить бренд</button>
        </form>

        <table class="table table-bordered table-striped mt-4"
               style="background-color: white; box-shadow: 0 0 15px rgba(0,0,0,0.1); border-radius: 8px; overflow: hidden;">
            <thead style="background-color: #f8f9fa;">
            <tr>
                <th>Имя Бренда</th>
                <th>Действия</th>
            </tr>
            </thead>
            <tbody>
            {% for brand in brands %}
                <tr>
                    <td>{{ brand.name }}</td>
                    <td>
                        <form method="POST" style="display:inline;">
                            {% csrf_token %}
                            <input type="hidden" name="brand_id" value="{{ brand.id }}">
                            <button type="submit" name="delete_brand" class="btn btn-red">Удалить</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/adminka/a_orders.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container mt-5">
        <h2 class="text-white text-center mb-4">Список заказов</h2>
        <table class="table table-bordered table-striped"
               style="background-color: white; box-shadow: 0 0 15px rgba(0,0,0,0.1); border-radius: 8px; overflow: hidden;">
            <thead style="background-color: #f8f9fa;">
            <tr>
                <th>Номер</th>
                <th>Пользователь</th>
                <th>Адрес</th>
                <th>Карта</th>
                <th>Статус</th>
            </tr>
            </thead>
            <tbody>
            {% for o in order %}
                <tr>
                    <td>{{ o.order_number }}</td>
                    <td>{{ o.username.username }}</td>
                    <td>{{ o.address }}</td>
                    <td>{{ o.card }}</td>
                    <td>
                        <form method="post" style="display:inline;">
                            {% csrf_token %}
                            <input type="hidden" name="order_id" value="{{ o.id }}">
                            <select name="status_id">
                                {% for status in statuses %}
                                    <option value="{{ status.id }}"
                                            {% if status.id == o.status.id %}selected{% endif %}>{{ status.name }}</option>
                                {% endfor %}
                            </select>
                            <button type="submit" class="btn btn-sm btn-primary">Обновить</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/adminka/a_product.html
{% extends "base.html" %}

{% block content %}
    <div class="container mt-5 bg-light p-4 rounded shadow">
        <h2 class="text-center mb-4">Изменить товар</h2>
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_name">Название продукта</label>
                        <input type="text" name="name" class="form-control" id="id_name" value="{{ product.name }}" required>
                    </div>
                    <div class="form-group">
                        <label for="id_price">Цена</label>
                        <input type="number" name="price" class="form-control" id="id_price" value="{{ product.price }}" required>
                    </div>
                    <div class="form-group">
                        <label for="description">Описание:</label>
                        <textarea class="form-control" id="description" name="description" rows="4">{{ product.description }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="id_photo">Фото</label><br>
                        <input type="file" name="photo" id="id_photo">
                    </div>
                    <div class="form-group">
                        <label for="id_quantity">Количество</label>
                        <input type="number" name="quantity" class="form-control" id="id_quantity" value="{{ product.quantity }}" required>
                    </div>
                    <div class="form-group">
                        <label for="category">Категория:</label>
                        <select class="form-control" id="category" name="category" required>
                            <option value="">Выберите категорию</option>
                            {% for category in categories %}
                                <option value="{{ category.id }}" {% if category.id == product.category.id %}selected{% endif %}>{{ category.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="id_brand">Бренд</label>
                        <select name="brand" class="form-control" id="id_brand" required>
                            {% for b in brands %}
                                <option value="{{ b.id }}" {% if b.id == product.brand.id %}selected{% endif %}>{{ b.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-red">Сохранить изменения</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/adminka/a_user.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container mt-5">
        <h2 class="text-white text-center mb-4">Список Продуктов</h2>
        <table class="table table-bordered table-striped"
               style="background-color: white; box-shadow: 0 0 15px rgba(0,0,0,0.1); border-radius: 8px; overflow: hidden;">
            <thead style="background-color: #f8f9fa;">
            <tr>
                <th>Имя</th>
                <th>Почта</th>
                <th>Дата</th>
                <th>Фото</th>
            </tr>
            </thead>
            <tbody>
            {% for u in users %}
                <tr>
                    <td>{{ u.username }}</td>
                    <td>{{ u.email }}</td>
                    <td>{{ u.date }}</td>
                    <td>{% if not u.profile_picture %}
                        <img src="{% static 'images/def.jpg' %}" class="rounded-circle mb-3"
                             style="width: 50px; height: 50px" alt="Avatar"/>
                    {% else %}
                        <img src="{{ u.profile_picture.url }}" class="rounded-circle mb-3"
                             style="width: 50px; height: 50px" alt="Avatar"/>
                    {% endif %}
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>


{% endblock %}

templates/adminka/adminka.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container mt-5 bg-light p-4 rounded shadow">
        <h2 class="text-center mb-4">Добавить новый товар</h2>
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <form action="{% url 'add_product' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="name">Название товара:</label>
                        <input type="text" class="form-control" id="name" name="name" required>
                    </div>
                    <div class="form-group">
                        <label for="price">Цена:</label>
                        <input type="number" class="form-control" id="price" name="price" required>
                    </div>
                    <div class="form-group">
                        <label for="photo">Изображение товара:</label>
                        <input type="file" class="form-control-file" id="photo" name="photo" accept="image/*">
                    </div>
                    <div class="form-group">
                        <label for="description">Описание:</label>
                        <textarea class="form-control" id="description" name="description" rows="4"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="quantity">Количество:</label>
                        <input type="number" class="form-control" id="quantity" name="quantity" required>
                    </div>
                    <div class="form-group">
                        <label for="category">Категория:</label>
                        <select class="form-control" id="category" name="category" required>
                            <option value="">Выберите категорию</option>
                            {% for category in categories %}
                                <option value="{{ category.id }}">{{ category.name }}</option>
                            {% endfor %}
                        </select>

                    </div>
                    <div class="form-group">
                        <label for="id_brand">Бренд</label>
                        <select name="brand" class="form-control" id="id_brand" required>
                            {% for b in brands %}
                                <option value="{{ b.id }}">{{ b.name }}</option>
                            {% endfor %}
                        </select>

                    </div>
                    <button type="submit" class="btn btn-red btn-block">Добавить товар</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}