orders/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *

urlpatterns = [
    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('checkout/', checkout, name='checkout'),
    path('order/create/<int:product_id>/', order_create, name='order_create'),
    path('orders/history', history, name='history'),
    path('add_address/', add_address, name='add_address'),
    path('add_cart/', add_cart, name='add_cart'),
    path('massage/', massage, name='massage'),
    path('delete_address/<int:address_id>/', delete_address, name='delete_address'),
    path('delete_card/<int:card_id>/', delete_card, name='delete_card'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopDiplom/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('www.urls')),
    path('authreg', include('authreg.urls')),
    path('orders', include('orders.urls')),
    path('adminka', include('adminka.urls')),
path('ratings/', include('star_ratings.urls', namespace='ratings')),
]

www/urls.py
from www.views import *
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', index, name='index'),
    path('shop', shop, name='shop'),  # This path does not require a category_id
    path('stocks', stocks, name='stocks'),
    path('cart', cart, name='cart'),
    path('remove_cart_item/<int:item_id>', remove_cart_item, name='remove_cart_item'),
    path('update_cart_item/<int:item_id>', update_cart_item, name='update_cart_item'),
    path('shop_single/<int:id>', shop_single, name='shop_single'),
    path('acc', acc, name='acc'),
    path('about', about, name='about'),
    path('orders', orders, name='orders'),
    path('products/category/<int:category_id>/', shop, name='products_by_category'),
    path('product/<int:id>/add_comment/', add_comment, name='add_comment'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from authreg.models import *
from www.models import *

class Address(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name="Пользователь")
    address = models.CharField(max_length=255, verbose_name="Адрес")

    def __str__(self):
        return self.address


class Card(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name="Пользователь")
    number = models.IntegerField(verbose_name="Номер карты")
    code = models.IntegerField(verbose_name="Код карты")
    date_cart = models.IntegerField(verbose_name="Срок действия карты")

    def __str__(self):
        return str(self.number)


class Status(models.Model):
    name = models.CharField(max_length=100, verbose_name="Статус заказа")

    def __str__(self):
        return self.name


import random

class Orders(models.Model):
    order_number = models.CharField(max_length=4, unique=True, blank=True, verbose_name="Номер заказа")
    username = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name="Пользователь")
    address = models.ForeignKey(Address, on_delete=models.CASCADE, verbose_name="Адрес")
    card = models.ForeignKey(Card, on_delete=models.CASCADE, verbose_name="Карта")
    status = models.ForeignKey(Status, on_delete=models.CASCADE, verbose_name="Статус")
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return f"{self.order_number} - {self.username.username}"

    def save(self, *args, **kwargs):
        if not self.order_number:
            self.order_number = self._generate_unique_order_number()
        super().save(*args, **kwargs)

    def _generate_unique_order_number(self):
        while True:
            num = f"{random.randint(1000, 9999)}"
            if not Orders.objects.filter(order_number=num).exists():
                return num


class OrderItem(models.Model):
    order = models.ForeignKey(Orders, related_name='items', on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="Продукт")
    quantity = models.IntegerField(verbose_name="Количество")

    def __str__(self):
        return str(self.quantity)


class Cart(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, verbose_name="Пользователь")

    @property
    def total_price(self):
        return sum(item.product.price * item.quantity for item in self.items.all())


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, related_name='items', on_delete=models.CASCADE, verbose_name="Корзина")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="Продукт")
    quantity = models.PositiveIntegerField(default=1, verbose_name="Количество")

orders/forms.py
from django import forms

from www.models import *
from .models import Address, Card

class OrderForm(forms.Form):
    address = forms.ModelChoiceField(queryset=Address.objects.none())
    card = forms.ModelChoiceField(queryset=Card.objects.none())

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['address'].queryset = Address.objects.filter(user=user)
        self.fields['card'].queryset = Card.objects.filter(user=user)



class OrderOneForm(forms.Form):
    address = forms.ModelChoiceField(queryset=Address.objects.none(), label='Адрес')
    card = forms.ModelChoiceField(queryset=Card.objects.none(), label='Карта')
    quantity = forms.IntegerField(min_value=1, initial=1, label='Количество')

    def __init__(self, *args, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields['address'].queryset = Address.objects.filter(user=user)
            self.fields['card'].queryset = Card.objects.filter(user=user)




class CardForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = ['number', 'code', 'date_cart']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text', 'rating']  # Поля, которые должны отображаться в форме
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Введите ваш комментарий'}),
            'rating': forms.RadioSelect(choices=[(i, str(i)) for i in range(1, 6)]),  # Рейтинг от 1 до 5
        }


orders/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

from .forms import *
from .models import *

from django.shortcuts import render, redirect
from .models import Orders, Product


def add_to_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    user = request.user
    quantity = int(request.POST.get('quantity', 1))

    cart, created = Cart.objects.get_or_create(user=user)
    cart_item = cart.items.filter(product=product).first()

    if cart_item:
        cart_item.quantity += quantity
        cart_item.save()
    else:
        CartItem.objects.create(cart=cart, product=product, quantity=quantity)

    return redirect('cart')


def order_create(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    if request.method == 'POST':
        form = OrderOneForm(request.POST, user=request.user)
        if form.is_valid():
            order = Orders.objects.create(
                username=request.user,
                address=form.cleaned_data['address'],
                card=form.cleaned_data['card'],
                status=Status.objects.get(name='В обработке')  # или нужный статус
            )

            OrderItem.objects.create(
                order=order,
                product=product,
                quantity=form.cleaned_data['quantity']
            )

            return redirect('orders')

    else:
        form = OrderOneForm(user=request.user)

    return render(request, 'index.html', {'form': form, 'product': product})


def checkout(request):
    cart = Cart.objects.get(user=request.user)
    total_price = sum(item.product.price * item.quantity for item in cart.items.all())

    if request.method == 'POST':
        form = OrderForm(request.user, request.POST)
        if form.is_valid():
            order = Orders.objects.create(
                username=request.user,
                address=form.cleaned_data['address'],
                card=form.cleaned_data['card'],
                status=Status.objects.get(name='В обработке')  # или соответствующий статус
            )
            for item in cart.items.all():
                OrderItem.objects.create(
                    order=order,
                    product=item.product,
                    quantity=item.quantity
                )
            cart.items.all().delete()  # Очистить корзину
            return redirect('massage')
    else:
        form = OrderForm(request.user)

    return render(request, 'orders/create.html', {'form': form, 'total_price': total_price})

def massage(request):
    return render(request, 'orders/massage.html')

def add_address(request):
    if request.method == 'POST':
        address = request.POST.get('address')
        Address.objects.create(address=address, user=request.user)
        referer = request.META.get('HTTP_REFERER')  # URL страницы, с которой пришёл запрос
        if referer:
            return redirect(referer)
        else:
            return redirect('acc')


def delete_address(request, address_id):
    address = get_object_or_404(Address, id=address_id, user=request.user)
    address.delete()
    return redirect('acc')


def add_cart(request):
    if request.method == 'POST':
        number = request.POST.get('number')
        code = request.POST.get('code')
        date_cart = request.POST.get('date_cart')
        Card.objects.create(number=number, code=code, date_cart=date_cart, user=request.user)

        referer = request.META.get('HTTP_REFERER')  # URL страницы, с которой пришёл запрос
        if referer:
            return redirect(referer)
        else:
            return redirect('acc')


def delete_card(request, card_id):
    card = get_object_or_404(Card, id=card_id, user=request.user)
    card.delete()
    return redirect('acc')


def history(request):
    orders = Orders.objects.filter(username=request.user, status__in=[3, 4])
    order_items = OrderItem.objects.filter(order__in=orders).select_related('product')

    product_ids = order_items.values_list('product__id', flat=True).distinct()
    comments = Comment.objects.filter(product__in=product_ids).order_by('-created_at')

    form = CommentForm()  # например, форма для добавления комментария

    context = {
        'products': order_items,
        'comments': comments,
        'form': form,  # передаем форму
    }
    return render(request, 'orders/history.html', context)

templates/orders/create.html
{% extends "base.html" %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <div class="border p-4 rounded bg-light shadow">
                    <form method="POST">
                        {% csrf_token %}
                        <h4 class="mb-4 text-center">Итоговая сумма: <span
                                class="font-weight-bold">{{ total_price }} р.</span></h4>

                        <div class="form-group">
                            <label for="id_address">Адрес</label>
                            <select name="address" class="form-control" id="id_address" required>
                                <option value="">Выберите адрес</option>
                                {% for address in form.address.field.queryset %}
                                    <option value="{{ address.id }}">{{ address }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <button type="button" class="btn btn-border mb-2" id="addAddressBtn">Добавить адрес</button>
                        <div class="form-group">
                            <label for="id_card">Карта</label>
                            <select name="card" class="form-control" id="id_card" required>
                                <option value="">Выберите карту</option>
                                {% for card in form.card.field.queryset %}
                                    <option value="{{ card.id }}">{{ card }}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <!-- Кнопки добавления адреса и карты под выпадающими списками -->

                        <button type="button" class="btn btn-border" id="addCardBtn">Добавить карту</button>

                        <button type="submit" class="btn btn-red btn-block mt-3">Заказать</button>
                    </form>

                    <!-- Модальное окно для добавления карты -->
                    <div id="addCardModal" class="modal" style="display:none;">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Добавить новую карту</h5>
                                    <button type="button" class="btn-close" aria-label="Close"
                                            onclick="closeCardModal()"></button>
                                </div>
                                <div class="modal-body">
                                    <form action="{% url 'add_cart' %}" method="POST">
                                        {% csrf_token %}
                                        <div class="mb-3">
                                            <label for="cardNumber" class="form-label">Номер карты</label>
                                            <input type="text" class="form-control" id="cardNumber" name="number"
                                                   required>
                                        </div>
                                        <div class="mb-3">
                                            <label for="cardCode" class="form-label">Код карты</label>
                                            <input type="text" class="form-control" id="cardCode" name="code" required>
                                        </div>
                                        <div class="mb-3">
                                            <label for="cardDate" class="form-label">Дата карты</label>
                                            <input type="text" class="form-control" id="cardDate" name="date_cart"
                                                   required>
                                        </div>
                                        <button type="submit" class="btn btn-primary">Сохранить карту</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Модальное окно для добавления адреса -->
                    <div id="addAddressModal" class="modal" style="display:none;">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Добавить адрес</h5>
                                    <button type="button" class="btn-close" aria-label="Close"
                                            onclick="closeAddressModal()"></button>
                                </div>
                                <div class="modal-body">
                                    <form action="{% url 'add_address' %}" method="POST">
                                        {% csrf_token %}
                                        <div class="mb-3">
                                            <label for="address" class="form-label">Адрес</label>
                                            <input type="text" class="form-control" id="address" name="address"
                                                   required>
                                        </div>
                                        <button type="submit" class="btn btn-red">Сохранить адрес</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

templates/orders/history.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container mt-5">
        <div class="row mb-5">

            {% for item in products %}
                <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
                    <div class="card h-100 text-black">
                        {% if not item.product.photo %}
                            <img src="{% static 'images/def.jpg' %}" class="card-img-top" alt="No photo available">
                        {% else %}
                            <img src="{{ item.product.photo.url }}" class="card-img-top" alt="{{ item.product.name }}">
                        {% endif %}
                        <div class="card-body">
                            <a href="{% url 'shop_single' item.product.id %}">
                                <h5 class="card-title">{{ item.product.name }}</h5>
                            </a>
                            <p class="card-text">
                                <strong class="item-price">{{ item.product.price }} р.</strong>
                            </p>
                            <p class="card-text">
                                <strong>Количество:</strong> {{ item.quantity }}
                            </p>
                            <p class="card-text">
                                <strong>Статус заказа:</strong> {{ item.order.status }}
                            </p>
                        </div>

                        <form method="POST" action="{% url 'add_comment' item.product.id %}"
                              class="p-3 border rounded bg-light">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="{{ form.text.id_for_label }}" class="form-label">Комментарий</label>
                                {{ form.text }}  <!-- Поле для текста -->
                                {% if form.text.errors %}
                                    <div class="text-danger">{{ form.text.errors }}</div>
                                {% endif %}
                            </div>

                            <div class="mb-3">
                                <label class="form-label">Рейтинг</label>
                                <div class="rating">
                                    {% for i in "54321" %}
                                        <input type="radio"
                                               id="star{{ i }}_{{ item.product.id }}"
                                               name="rating"
                                               value="{{ i }}"
                                               {% if form.rating.value|stringformat:"s" == i %}checked{% endif %}/>
                                        <label for="star{{ i }}_{{ item.product.id }}"
                                               title="{{ i }} звезда">&#9733;</label>
                                    {% endfor %}
                                </div>

                                {% if form.rating.errors %}
                                    <div class="text-danger">{{ form.rating.errors }}</div>
                                {% endif %}
                            </div>

                            <button type="submit" class="btn btn-red">Добавить комментарий</button>
                        </form>


                        <div id="successMessage" style="display: none;" class="alert alert-success mt-3">
                            Спасибо за ваш комментарий!
                        </div>

                        <script>
                            document.getElementById('commentForm').addEventListener('submit', function (event) {
                                event.preventDefault(); // Останавливаем стандартное поведение формы

                                // Отправляем данные формы через Fetch API
                                const formData = new FormData(this);
                                fetch(this.action, {
                                    method: 'POST',
                                    body: formData,
                                    headers: {
                                        'X-CSRFToken': '{{ csrf_token }}'
                                    }
                                })
                                    .then(response => {
                                        if (response.ok) {
                                            // Скрываем форму и показываем сообщение об успехе
                                            document.getElementById('commentForm').style.display = 'none';
                                            document.getElementById('successMessage').style.display = 'block';
                                        } else {
                                            alert('Ошибка при отправке комментария. Попробуйте снова.');
                                        }
                                    })
                                    .catch(error => {
                                        console.error('Ошибка:', error);
                                        alert('Произошла ошибка. Попробуйте снова.');
                                    });
                            });
                        </script>


                    </div>
                </div>
            {% empty %}
                <p class="text-white">Нет товаров для отображения.</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}


templates/orders/massage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container success-container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="alert alert-success text-center" role="alert"><h4 class="alert-heading">Заказ успешно
                    оформлен!</h4>
                    <p>Спасибо за ваш заказ. Мы получили его и начнем обработку в ближайшее время.</p>
                    <hr>
                    <p class="mb-0">Номер вашего заказа: <strong>#123456</strong></p></div>
                <div class="text-center"><a href="/" class="btn btn-red">Вернуться на главную</a> <a href="/orders"
                                                                                                         class="btn btn-border">Просмотреть
                    заказы</a></div>
            </div>
        </div>
    </div>
{% endblock %}

templates/orders/order_success.html
{% extends "base.html" %}

{% load static %}
{% block content %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-12">
                <h2 class="text-white text-center mb-4">Ваши Заказы</h2>
                {% for order in orders %}
                    <div class="card mb-3"> <!-- Установите максимальную высоту -->
                        <div class="card-header">
                            <h5 class="mb-0" style="font-size: 1rem;">Заказ №{{ order.order_number }} —
                                Статус: {{ order.status }}</h5>
                        </div>
                        <div class="card-body pl-4 pr-4 pb-3" style="padding: 0.5rem;"> <!-- Уменьшите отступы -->
                            <p style="font-size: 0.9rem;"><strong>Адрес:</strong> {{ order.address }}</p>
                            <h6 style="font-size: 0.9rem;">Содержимое заказа:</h6>
                            {% for item in order.items.all %}
                                
                                <a class="d-flex align-items-center mb-3" href="{% url 'shop_single' item.id %}">
                                    <div class="d-flex justify-content-between w-100">
                                        <div class="d-flex align-items-center">
                                            <div>
                                                {% if not item.product.photo %}
                                                    <img style="width: 64px; height: auto;"
                                                         src="{% static 'images/def.jpg' %}" class="card-img-top"
                                                         alt="No photo available">
                                                {% else %}
                                                    <img style="width: 64px; height: auto;"
                                                         src="{{ item.product.photo.url }}" class="card-img-top"
                                                         alt="{{ item.product.name }}">
                                                {% endif %}
                                            </div>
                                            <div class="ms-3">
                                                <h5 class="mb-0">{{ item.product.name }}</h5>
                                            </div>
                                        </div>

                                        <div class="d-flex flex-column align-items-end mt-3">
                                            <p class="card-text mb-0" style="font-size: 0.8rem;">
                                                <h6 class="item-price">Количество: {{ item.quantity }}</h6>
                                            </p>
                                        </div>
                                        <div class="d-flex flex-column align-items-end mt-3">
                                            <p class=" mb-0">{{ item.product.price }} p.</p>
                                        </div>
                                    </div>
                                </a>

                            {% endfor %}
                        </div>
                    </div>
                {% empty %}
                    <div class="alert alert-info" role="alert">
                        У вас пока нет заказов.
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}